language: python
sudo: false
python:
  - 3.6
  - 3.7

env:
  - DJANGO=2.1
  - DJANGO=2.2


install:
  - pip install tox codecov

script:
  - tox -e "d${DJANGO//.}-py${TRAVIS_PYTHON_VERSION//.}"

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
